# Generated by Django 4.1.4 on 2022-12-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registeration',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registeration',
            name='pincode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
